"""
VIBRANIUM AI - System Test Script
Tests all components of the AI pipeline
"""

import json
import sys
from pathlib import Path

# Add paths
sys.path.append(str(Path(__file__).parent))

print("="*70)
print("VIBRANIUM AI - System Test")
print("="*70)
print()

# Test 1: Load sample data
print("Test 1: Loading sample data...")
try:
    with open('datasets/sample_reviews.json', 'r') as f:
        review_data = json.load(f)
    
    with open('datasets/competitors.json', 'r') as f:
        competitor_data = json.load(f)
    
    print(f"✓ Loaded {len(review_data['products'])} products with reviews")
    print(f"✓ Loaded {len(competitor_data['competitors'])} competitor categories")
    print()
except Exception as e:
    print(f"✗ Failed to load data: {str(e)}")
    sys.exit(1)

# Test 2: Sentiment Analyzer
print("Test 2: Testing Sentiment Analyzer...")
try:
    from models.sentiment_analyzer import SentimentAnalyzer
    
    analyzer = SentimentAnalyzer()
    
    # Test single text
    test_text = "This product is amazing and works perfectly!"
    result = analyzer.analyze_text(test_text)
    print(f"✓ Single text analysis: Score = {result['sentiment_score']}/100")
    
    # Test multiple reviews
    sample_product = review_data['products'][0]
    multi_result = analyzer.analyze_reviews(sample_product['reviews'])
    print(f"✓ Multiple reviews analysis: Overall score = {multi_result['overall_sentiment_score']}/100")
    print(f"  Positive: {multi_result['positive_count']}, Negative: {multi_result['negative_count']}, Neutral: {multi_result['neutral_count']}")
    print()
except Exception as e:
    print(f"✗ Sentiment analyzer failed: {str(e)}")
    print()

# Test 3: Feature Extractor
print("Test 3: Testing Feature Extractor...")
try:
    from models.feature_extractor import FeatureExtractor
    
    extractor = FeatureExtractor()
    
    sample_product = review_data['products'][0]
    result = extractor.extract_features_from_reviews(sample_product['reviews'])
    
    print(f"✓ Feature extraction complete")
    print(f"  Total feature mentions: {result['total_feature_mentions']}")
    print(f"  Top categories: {[cat['category'] for cat in result['top_feature_categories'][:3]]}")
    print()
except Exception as e:
    print(f"✗ Feature extractor failed: {str(e)}")
    print()

# Test 4: Insight Generator
print("Test 4: Testing Insight Generator...")
try:
    from models.insight_generator import InsightGenerator
    
    generator = InsightGenerator()
    
    insights = generator.generate_product_insights(
        product_name="Test Product",
        sentiment_score=75.0,
        features=["quality", "design", "performance"],
        review_summary={
            "total_reviews": 10,
            "positive_count": 7,
            "negative_count": 2,
            "neutral_count": 1
        }
    )
    
    print(f"✓ Insight generation complete")
    print(f"  Generated by: {insights['generated_by']}")
    print(f"  Recommendation type: {insights['recommendation_type']}")
    print()
except Exception as e:
    print(f"✗ Insight generator failed: {str(e)}")
    print()

# Test 5: Analysis Pipeline
print("Test 5: Testing Analysis Pipeline...")
try:
    from pipelines.analysis_pipeline import AnalysisPipeline
    
    pipeline = AnalysisPipeline()
    
    sample_product = review_data['products'][0]
    result = pipeline.analyze_product(
        product_name=sample_product['productName'],
        reviews=sample_product['reviews'],
        product_metadata={
            "category": sample_product['category']
        }
    )
    
    print(f"✓ Analysis pipeline complete")
    print(f"  Product: {result['product_name']}")
    print(f"  Sentiment Score: {result['sentiment_analysis']['overall_score']}/100")
    print(f"  Features Found: {len(result['feature_analysis']['extracted_features'])}")
    print()
except Exception as e:
    print(f"✗ Analysis pipeline failed: {str(e)}")
    print()

# Test 6: Competitor Pipeline
print("Test 6: Testing Competitor Pipeline...")
try:
    from pipelines.competitor_pipeline import CompetitorPipeline
    
    comp_pipeline = CompetitorPipeline()
    
    # Get electronics category data
    electronics_data = None
    for category in competitor_data['competitors']:
        if category['category'] == 'Electronics':
            electronics_data = category['products']
            break
    
    if electronics_data:
        target = electronics_data[0]
        competitors = electronics_data[1:3]
        
        result = comp_pipeline.compare_products(target, competitors)
        
        print(f"✓ Competitor pipeline complete")
        print(f"  Target: {result['target_product']['name']}")
        print(f"  Competitors analyzed: {result['competitors_analyzed']}")
        print(f"  Feature gaps identified: {result['feature_gaps']['total_gaps']}")
        print(f"  Market position: {result['overall_position']['tier']}")
        print()
except Exception as e:
    print(f"✗ Competitor pipeline failed: {str(e)}")
    print()

# Summary
print("="*70)
print("Test Summary")
print("="*70)
print()
print("✓ All core components tested successfully!")
print()
print("Next steps:")
print("1. Start the API server: cd api && python main.py")
print("2. Access API docs: http://localhost:8000/docs")
print("3. Test endpoints using the interactive Swagger UI")
print()
print("="*70)
